version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nextapp
    file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ubuntu