version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:  
    commands:
      - npm install
      - npm run build

artifacts:
    base-directory: .next
    files:
      - '**/*'
